name = "ModalIsolationForest"
uuid = "d0fc4cbc-50a4-4382-9dfb-5921de651e35"
authors = ["Eduard I. STAN", "Giovanni PAGLIARINI"]
version = "1.0.0-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
